; BOOT.ASM: BOOTLOADER
[bits 32] ; 32 BIT
extern _kernel_main ; MAIN IS IN CPP FILE AND SHOULD BE LINKED
; NEEDED BY BOOTLOADERS SUCH AS GRUB
section .mbHeader
align 0x4

; MULTIBOOT HEADER - SEE GRUB DOCS FOR DETAILS
MODULEALIGN equ 1<<0
MEMINFO equ 1<<1
FLAGS equ MODULEALIGN | MEMINFO
MAGIC equ 0x1BADB002
CHECKSUM equ -(MAGIC + FLAGS)

MULTIBOOTHEADER:
    dd MAGIC
    dd FLAGS
    dd CHECKSUM

global start ; START OPERATING SYSTEM
start:
call _kernel_main
